-- 0001_core.sql — tenants and platform settings.
--
-- Base column set and conventions per docs/design/02. Database Schema.md §1;
-- table definitions per §2. UUIDs are generated by the application (v7,
-- time-ordered), so no database-side default is declared.

CREATE TABLE tenants (
    id              UUID        PRIMARY KEY,
    tenant_code     TEXT        NOT NULL,           -- TNT-001
    name            TEXT        NOT NULL,
    status          TEXT        NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE')),
    settings_json   JSONB       NOT NULL DEFAULT '{}',
    created_by      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by      UUID,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT uq_tenants_tenant_code UNIQUE (tenant_code)
);

-- Platform-level and per-tenant configuration that is not RAD metadata:
-- feature toggles, defaults, limits.
--
-- created_by / updated_by reference users (id), but 0002_identity.sql creates
-- that table; the foreign keys are added there rather than forward-declared.
CREATE TABLE system_settings (
    id              UUID        PRIMARY KEY,
    tenant_id       UUID        NOT NULL REFERENCES tenants (id),
    created_by      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by      UUID,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    setting_key     TEXT        NOT NULL,
    setting_value   JSONB       NOT NULL,
    is_secret       BOOLEAN     NOT NULL DEFAULT false,
    description     TEXT
);

CREATE UNIQUE INDEX uq_system_settings_tenant_id_setting_key
    ON system_settings (tenant_id, setting_key) WHERE deleted_at IS NULL;

CREATE INDEX idx_system_settings_tenant_id
    ON system_settings (tenant_id) WHERE deleted_at IS NULL;

-- The reserved system tenant owns platform-level rows (schema §1.5). Its UUID
-- is fixed so seed data and migrations can reference it without a lookup.
INSERT INTO tenants (id, tenant_code, name, status)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'SYSTEM',
    'Kelir Platform',
    'ACTIVE'
);
